### PR TITLE
feat: set server cpu and memory requests and limits via CLI

### PR DESCRIPTION
**Pull request by mindovermiles262**
Per #118 this PR allows end users to specify the server's CPU and Memory Requests and Limits.

Please let me know if you have any questions or need anything from me to get this approved and merged. Thanks for this program - super helpful :)

### CODE REVIEW

**Comment by mindovermiles262** [comment]
Hi @omrikiei ,

I updated this branch to fix the merge conflicts. I'd love to get some comments on this or get it merged into ktunnel so I can start using it with my project. Please let me know if you have any questions or comments.

Thank you!

**Comment by omrikiei** [comment]
Done, sorry for the delay

**Comment by mindovermiles262** [comment]
Thank you!

**Comment by idsulik** [comment]
@omrikiei hi! Could you please create a new release?

**Pull request merged**
